---
title: "Research"
---

###Working Papers:

#### Search and Matching In Overlapping Generations Model

Download: Two-Page Summary; Poster; Working Paper

**Abstract**: Previous overlapping generations models studying the effects of Social Security reforms mainly focus on saving, labor supply and consumption decisions by employed individuals. To study how fiscal reforms and economy's labor market conditions affect the the behavior of unemployed, I develop a novel general equilibrium overlapping generations model with labor market frictions and endogenous transition between labor market states. Besides the typical decisions of saving and consumption, non-employed make a decision whether to stay in the labor force (as unemployed) and if so, how much effort to put in the job search while firms endogenously post optimal number of vacancies. As Social Security is approaching inevitable reforms, I use this general equilibrium model to examine what effect the stylized fiscal reforms may have on the non-employed workers behavior and what ramifications their behavior has for the rest of the population. While the results, in general, are in line with previous research, the model suggests a substantial feedback effect between change in the number of unemployed and number of posted vacancies that magnifies the long term beneficial outcomes of policies encouraging labor force participation and private saving. Similarly, the negative outcomes of labor and saving disincentivizing policies, such as increased income or capital gains taxation, are also magnified. In addition, I find that there is significant competition between heterogeneous groups of unemployed agents: a larger change in search decisions of one group of unemployed have an effect on job search decisions of the rest of unemployed agents.

\


#### Hiring Subsidies and Aging in an Economy with Hidden Labor Market

Download: Two-Page Summary; Poster; Working Paper

**Abstract**: Due to population aging coupled with low median savings, increasing number of elderly Americans will need to work past a typical current retirement age despite facing old age discrimination. Among the policies, that could increase the firms' demand of elderly labor, are hiring and wage subsidies for older workers. I examine these labor market policies in a computable overlapping generations model with labor market frictions. I find that hiring subsidies increase employment of workers in the targeted age range but at a cost of lower employment of younger workers. The model indicates relatively large employment and welfare costs associated with these policies, especially when they are financed by labor income or consumption taxes, or by decreasing social security. Welfare costs are lower when capital gains tax is utilized to finance the subsidy.

\


#### Hiring Subsidies in an Economy with Hidden Labor Market

Download: Two-Page Summary; Interactive Summary; Poster; Working Paper

Presented at The New York State Economic Association 71st Annual Conference (Fall, 2018)\
Presented at 2019 Eastern Economic Association (March, 2019)\
Presented at the 4th International ESS Conference (April, 2019)

**Abstract**: The size of the shadow or hidden economy in European countries varies from 10 to 30 percent of the GDP. I identify hidden laborers using European Social Survey and show that hidden labor market in European countries exhibits U-shape age profile. I build a general equilibrium overlapping generations model with labor market frictions, hidden labor market and endogenous retirement to re-examine two policy reforms, unemployment insurance and hiring subsidies. The model is able to replicate the formal and undeclared labor market participation rates found in major European countries. Contrary to some previous research, I .find unemployment insurance having a limited effect on the hidden labor market activity as majority of the participants are very young and the very old. Hiring subsidies, however, are able to significantly reduce hidden labor market participation of the elderly significantly improving the well-being of the elderly at a small cost to the younger workers. This paper provides additional support for use of hiring subsidies to encourage elderly labor market participation and well-being in old age.